---
- name: terminate single instance
  hosts: "{{ instance_tag }}"
  tasks:
    - action: ec2_facts
    - name: terminating single instance
      local_action:
        module: ec2
        state: 'absent'
        region: eu-central-1
        instance_ids: "{{ ansible_ec2_instance_id }}"

